name: GameTime
version: 1.6.1
authors: [a,asougi85]
depend: [ProtocolLib]
softdepend: [AuthMe,CrazyLogin,xSignIn,Login,PlaceholderAPI]
main: com.shader.gt.GameTime

permissions: 
  gametime.gt: 
    default: op
    
  gametime.help: 
    default: true
    
  gametime.use: 
    default: true
    
  gametime.check: 
    default: true
    
  gametime.checkother: 
    default: op
    
  gametime.checkkey: 
    default: op